### ISSUE TITLE
Form validation and helper text on user input forms

### ISSUE THREAD

**Issue by tenthirtyone** [unicef/juniper-portfolio#257]
wallets, accounts, and settings

**Comment by upretiprateek** [comment]
@tenthirtyone finding this a little confusing. Could you give a screenshot of the page where the change is required?

**Comment by tenthirtyone** [comment]
@upretiprateek This would be all of the forms in the application that take user input - Adding wallets, accounts, and editing/tagging transactions

**Comment by tenthirtyone** [comment]
From #359

I do need the requirements per form or per form field based on type - 'name' 'address' etc. and this can probably track the form change to the manual amount entries noted in here: #357

**Comment by tenthirtyone** [comment]
@mehranhydary I'd say a minimum can be required fields and required formatting on any fields should be the quickest way. 

Eth/USD will use app wide settings unless otherwise. Anything you can think of that I am missing?
