### ISSUE TITLE
Add user type to user list on settings page

### ISSUE THREAD

**Issue by tenthirtyone** [unicef/juniper-portfolio#265]

**Comment by upretiprateek** [comment]
@tenthirtyone is this list required in ‘View existing users’ section? also are you aware of the user types?

**Comment by tenthirtyone** [comment]
@upretiprateek Admin & User I guess. @CriLoma for clarification

**Comment by tenthirtyone** [comment]
@upretiprateek This looks like an edit users feature. I think this ticket just needs the user type (Admin/User) added to the View Existing Users list
