### ISSUE TITLE
Create a footer for the page that will have the btc price, eth price, and the disclaimer

### ISSUE THREAD

**Issue by tenthirtyone** [unicef/juniper-portfolio#267]

**Comment by upretiprateek** [comment]
@tenthirtyone the daily price information is being displayed in the left panel, as per the updated design. Any reason why this needs to be in the footer and not the left panel?
Also do you have the text copy for the disclaimer?
<img width="1260" alt="Screenshot 2020-10-28 at 3 29 03 PM" src="https://user-images.githubusercontent.com/47604754/97421310-5d576580-1932-11eb-9044-62552e093fea.png">

**Comment by upretiprateek** [comment]
@tenthirtyone uploaded the new screen on Zeplin: https://zpl.io/VKrNdPW

Things that have changed:
* The USD price conversion banner at the top of each screen has been integrated in the left side panel.  When the user clicks on the blue button 'USD price calculation', it opens up this popup: https://zpl.io/2vw7vQ5
