### ISSUE TITLE
BUG/COPY: Text is not the same when viewing in a compressed window as a normal window

### ISSUE THREAD

**Issue by CriLoma** [unicef/juniper-portfolio#309]
On the Invest page, when I'm looking at the numbers, if I'm looking at it full screen it says 12 investments, but when I make my window smaller, it says 11

![image](https://user-images.githubusercontent.com/49003323/97512185-454a0b00-195f-11eb-91b7-d68868416d59.png)
![image](https://user-images.githubusercontent.com/49003323/97512210-52ff9080-195f-11eb-8857-8b3faf6f4cd0.png)

**Comment by tenthirtyone** [comment]
Closing 

@mehranhydary This needs to go to: https://github.com/unicef/juniper-visual

Repo is currently private =)
