### ISSUE TITLE
Low priority: issue with logo upload

### ISSUE THREAD

**Issue by CriLoma** [unicef/juniper-portfolio#348]
If I upload a logo which has a transparent background and white text (which is the type of text that is preferred for it to show up nicely in Juniper), you can then not see your logo in the admin dashboard. 

I am including the file I tested with. (its just below... you also can't see it here haha)
![UNICEF Innovation_Primary Logo_White_RGB (1)](https://user-images.githubusercontent.com/49003323/102663399-cc8d5100-414e-11eb-8ac8-d6c80063740d.png)

![image](https://user-images.githubusercontent.com/49003323/102663379-c008f880-414e-11eb-8524-10d98cd503bd.png)

**Comment by tenthirtyone** [comment]
added theme primary color as the background for the image to give a real preview and have something to fill in the transparency.
