### ISSUE TITLE
Following users: update required

### ISSUE THREAD

**Issue by mehranhydary** [unicef/juniper-portfolio#358]
# Wallets page 
Update is required on the `Track Wallets` section of this page; confirming the business requirements here in this issue.
## Track Wallets
1. Only admin users should be able to see the "FOLLOW A BLOCKCHAIN WALLET" button
<img width="527" alt="Screen Shot 2021-01-06 at 1 34 25 PM" src="https://user-images.githubusercontent.com/2007405/103807105-efab7200-5023-11eb-9789-a1d157d54225.png">
2. Hide the "Other Wallets" section for all users. This includes the wallets under it as well.
<img width="527" alt="Screen Shot 2021-01-06 at 1 35 09 PM" src="https://user-images.githubusercontent.com/2007405/103807189-0e116d80-5024-11eb-8cae-9186656878d4.png">
3. The wallets that appear under "FOLLOWING N WALLETS" should show the current balance of the wallet (I think it does it already; just confirm)
<img width="276" alt="Screen Shot 2021-01-06 at 1 36 15 PM" src="https://user-images.githubusercontent.com/2007405/103807287-313c1d00-5024-11eb-8c87-f4aa097aef6a.png">
4. The wallets that are added by an admin with the "FOLLOW A BLOCKCHAIN WALLET" button should show for all users (admin and general).

**Comment by mehranhydary** [comment]
@tenthirtyone @CriLoma pls review and lmk if I missed anything before Alex kicks off dev

**Comment by CriLoma** [comment]
Correct. We're aligned.

**Comment by tenthirtyone** [comment]
Only Admins can Follow A Blockchain Wallet

Followed wallets are visible to all users.

Followed Wallets should display the current wallet balance (Same formatting rules as in accounts?)

Remove Other Wallets section


What happens when a wallet is followed that is already somewhere else in the database (Donor, Payee, Natcom, HQ Wallet)?

**Comment by mehranhydary** [comment]
Only Admins can Follow A Blockchain Wallet - Yes

Followed wallets are visible to all users - Yes

Followed Wallets should display the current wallet balance (Same formatting rules as in accounts?) - Can I think just update the card text in the Track Wallets page to show "Account Balance" instead of showing "ETH sent, received, etc.". Let me know if you need clarification on this.

Remove Other Wallets section - Yes

What happens when a wallet is followed that is already somewhere else in the database (Donor, Payee, Natcom, HQ Wallet)? - Nothing; let's keep the two separate for now since we are only showing balances on the Track Wallets page.
