### ISSUE TITLE
Form validation required on forms

### ISSUE THREAD

**Issue by mehranhydary** [unicef/juniper-portfolio#359]
Large issue - please add validation on all forms on the platform

**Comment by mehranhydary** [comment]
@tenthirtyone - let me know if you need me to flesh this out with a bit more detail (i can go into the app, find all the forms and mention the type of validation that is required)

**Comment by tenthirtyone** [comment]
Closing as a dupe: https://github.com/unicef/juniper-portfolio/issues/257

I do need the requirements per form or per form field based on type - 'name' 'address' etc. and this can probably track the form change to the manual amount entries noted in here: https://github.com/unicef/juniper-portfolio/issues/357
