### ISSUE TITLE
ISSUE: Price data is not being pulled correctly under Accounts

### ISSUE THREAD

**Issue by CriLoma** [unicef/juniper-portfolio#379]
Under the Transactions Page, not all prices are calculated using the appropriate day. 

For example, Huobi sent crypto on 12 Feb in the amount of 0.0100 BTC. If you calculate the value of that based on the Price Tracker (ie at the value of 1 BTC = 47,253.93 on 12 Feb), then the USD value of 0.01 BTC should be $472.54. HOWEVER, the amount that shows up in the transactions page in 479.45 (it is in fact pulling the price for Feb 13th). *Note, not all values are pulling from the incorrect day. Huobi's transation of 6.99 BTC is valued corrected, using the correct price 

![image](https://user-images.githubusercontent.com/49003323/110014173-7ca33c80-7cf0-11eb-9cdb-1b7429050cb5.png)

**Comment by tenthirtyone** [comment]
I think this is timezone related between the stored price date and transaction date. 

Using the 13th's price of $47,944.51 = 479.4451

**Comment by tenthirtyone** [comment]
Ok this was actually easy but a long trace. Javascript defaults to the local computers timezone and automatically converts the timestamp value. Everything after UTC was using the locale time zone - "Crypto received at 2:57 UTC, Sat, February 13, 2021" 

I confirmed this against blockchain.com:
![image](https://user-images.githubusercontent.com/6285466/110983041-45a7d900-8337-11eb-95fc-b86277d9a579.png)

It was seen on the 12th in the EST timezone, but at 9:57PM. Formatting the string to use the UTC day correctly accounts for timezones in the string and the updated Feb 13th price of $47,944.51 = 479.4451 is correct.

This one was fun.
