### ISSUE TITLE
ISSUE: For a donor, the total value received is not summing properly 

### ISSUE THREAD

**Issue by CriLoma** [unicef/juniper-portfolio#380]
On the Accounts Page, when I am looking at the total value that the donor has given, it does not add up to the two transactions listed in the account page.

For example, For Huobi, they donated 7 BTC. This was from 2 transactions, which are listed below. When you add them up, they don't sum to the Total Value at Receipt at the top of the page

![image](https://user-images.githubusercontent.com/49003323/110014649-0d7a1800-7cf1-11eb-89cf-455c6c2e9f4a.png)

**Comment by tenthirtyone** [comment]
Oh this is a good one. The current value / val @ receipt are just flipped. We fixed eth for this a while back but I wasnt testing against btc.

**Comment by DivyanshiSingh** [comment]
Is this issue still exists. @CriLoma @mehranhydary @tenthirtyone can you please point me on this.
