### ISSUE TITLE
ISSUE: Under Accounts, the date of transactions is not showing up correctly

### ISSUE THREAD

**Issue by CriLoma** [unicef/juniper-portfolio#381]
When I am inside the details of an account (donor), the dates listed for the transaction are incorrect. Under the Huobi account, it says 3 Feb, 5 Feb, when in fact the transactions were 12 Feb and 17 Feb 

![image](https://user-images.githubusercontent.com/49003323/110014854-46b28800-7cf1-11eb-8c46-6be61a13c626.png)

**Comment by tenthirtyone** [comment]
Ah I think I used the function to pull the day of the week and not the day of the month.

Yup. Fix going up

**Comment by DivyanshiSingh** [comment]
As I can see this issue is reopened. So want to ask @mehranhydary @tenthirtyone @CriLoma that is this issue still open for working?
