### ISSUE TITLE
ISSUE: Current Value does not add up when you use the "Today's Price" details to calculate against a BTC value

### ISSUE THREAD

**Issue by CriLoma** [unicef/juniper-portfolio#382]
When I'm in the Account page, if I try to use the "Today's Price" (in the bottom left) against the amount of crypto donated, the "Current Value" does not match up. 

I should be able to use "Today's Price" and multiply it by the amount received and the Current Value should be displayed

![image](https://user-images.githubusercontent.com/49003323/110015676-220ae000-7cf2-11eb-8385-c28b16b209b1.png)

**Comment by CriLoma** [comment]
This also seems to be a problem for Ethereum Prices under the Accounts section 


![image](https://user-images.githubusercontent.com/49003323/110016211-c5f48b80-7cf2-11eb-9bc1-bf4190e55c1a.png)

**Comment by tenthirtyone** [comment]
This has also been fixed in PR #384 because these are downstream. I believe it was using the same unrounded numbers and because that is taking place on the server now it should align.
