### ISSUE TITLE
Adding more content to README.md for more clarity in set up of the project 

### ISSUE THREAD

**Issue by DivyanshiSingh** [unicef/juniper-portfolio#390]
An ALCHEMY API key is also needed to set up the .env.example file.
What do you think about this @mehranhydary @tenthirtyone

**Comment by mehranhydary** [comment]
You should be able to create one here: https://www.alchemyapi.io/

Please update the README to include these details :)

**Comment by DivyanshiSingh** [comment]
Ok sure, working on this, will raise the PR soon.
