### ISSUE TITLE
Add links for the prereuisites in the readme

### ISSUE THREAD

**Issue by Aaishpra** [unicef/juniper-portfolio#392]
Add links for the bullet points under the Prerequisites section for ease of setup and correct the spelling of the heading `Prerequisites.`(currently written as `Prerequisittes)`
Example: add a link for making an account on Amazon web services

**Comment by Aaishpra** [comment]
@mehranhydary can you confirm the issue and assign me?

**Comment by mehranhydary** [comment]
Thanks for raising - going to address this (and other updates required in the README) in a new issue
