### ISSUE TITLE
Update: Change list in the Setting page for the form that adds new users

### ISSUE THREAD

**Issue by mehranhydary** [unicef/juniper-portfolio#396]
The list allows users to select what team the person being added to the platform. The list currently has DFAM, Office of Innovation, ICTD, Operations (OOI), and WASH.

The list should be updated so that have DFAM, Office of Innovation, ICTD, Supply Division (i.e. remove WASH and Operations (OOI) and add Supply Division)

**Comment by tenthirtyone** [comment]
Fixed in https://github.com/unicef/juniper-portfolio/pull/404
