### ISSUE TITLE
Update Required: Tag Transactions Button needs fixing

### ISSUE THREAD

**Issue by mehranhydary** [unicef/juniper-portfolio#416]
1. "Tag Transactions" button should take user to the "Accounts" page (user can create account there)

**Comment by mehranhydary** [comment]
For the issue:
1. I think right now it opens a modal in the transactions page
2. Instead of doing that, have it take the user to the accounts page
3. That's it lol - if they want to create a new account, they can do it there and then our app would auto tag the tx

**Comment by tenthirtyone** [comment]
Fixed in https://github.com/unicef/juniper-admin/pull/3
